/**
 * @typedef {Object} Aggregated_IoT_Data
 * @property {String} device_name - The IoT device name
 * @property {String} date - First 10 characters of a Date.toIsoString() generated by JavaScript.
 * @property {Array} data - Array of Objects containing timestamped IoT device readings.
 *
 */
